// import React from 'react';
// import { type NextPage } from "next";
// import Head from "next/head";
// import Link from "next/link";
// import Header from "../components/header"
// import Footer from "../components/footer"

// const About: NextPage = () => {
//   return (
//     <>
//       <Head>
//         <title>Macrovesta</title>
//         <meta name="description" content="Generated by Macrovesta" />
//         <link rel="icon" href="/favicon.ico" />
//         {/* <script src="/static/datafeeds/udf/dist/bundle.js" async /> */}
//         <link rel="alternate" hrefLang="en" href="https://www.macrovesta.ai" />
//         <link rel="alternate" hrefLang="pt-br" href="https://pt-br.macrovesta.ai" />
//         <link rel="alternate" hrefLang="es" href="https://es.macrovesta.ai" />
//         <link rel="alternate" hrefLang="tr" href="https://tr.macrovesta.ai" />
//         <link rel="alternate" hrefLang="th" href="https://th.macrovesta.ai" />
//         {/* <script type="text/javascript" src="https://cdn.weglot.com/weglot.min.js"></script>
//         <script>
//           {Weglot.initialize({
//             api_key: 'wg_60b49229f516dee77edb3109e6a46c379'
//           })}
//         </script> */}
//       </Head>
//       <Header />
//       <div className='h-screen'></div>

//       <Footer />
//     </>
//   )
// }

// export default About


import React, { useEffect, useState, useRef } from 'react';
import Header from '../components/header';
import Footer from '../components/footer';
import SlideInImage from '../components/slideInImage'
import CookieConsent from '../components/cookieConsent';
import Head from "next/head";
import Link from "next/link";

export const metadata = {
  title: 'About',
  description: 'Learn more about The Rubbish Portal',
};

export default function About() {
  return (
    <>
      <Head>
        <title>Macrovesta</title>
        <meta name="description" content="Generated by Macrovesta" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="/static/datafeeds/udf/dist/bundle.js" async /> */}
        <link rel="alternate" hrefLang="en" href="https://www.macrovesta.ai" />
        <link rel="alternate" hrefLang="pt-br" href="https://pt-br.macrovesta.ai" />
        <link rel="alternate" hrefLang="es" href="https://es.macrovesta.ai" />
        <link rel="alternate" hrefLang="tr" href="https://tr.macrovesta.ai" />
        <link rel="alternate" hrefLang="th" href="https://th.macrovesta.ai" />
        {/* <script type="text/javascript" src="https://cdn.weglot.com/weglot.min.js"></script>
        <script>
          {Weglot.initialize({
            api_key: 'wg_60b49229f516dee77edb3109e6a46c379'
          })}
        </script> */}
      </Head>
      <Header />
      <CookieConsent />
      <div className="animate-slidedown relative isolate overflow-hidden bg-gradient-to-tr from-deep_blue to-navy py-24 sm:py-32">
        <div className="hidden sm:absolute sm:-top-10 sm:right-1/2 sm:-z-10 sm:mr-10 sm:block sm:transform-gpu sm:blur-3xl animate-expand" aria-hidden="true">
          <div className="aspect-[1097/845] w-[68.5625rem] bg-gradient-to-tr  from-navy to-deep_blue opacity-30" style={{ clipPath: 'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)' }}></div>
        </div>
        <div className="absolute -top-52 left-1/2 -z-10 -translate-x-1/2 transform-gpu blur-3xl sm:top-[-28rem] sm:ml-16 sm:translate-x-0 sm:transform-gpu animate-expand" aria-hidden="true">
          <div className="aspect-[1097/845] w-[68.5625rem] bg-gradient-to-tr  from-navy to-deep_blue opacity-30" style={{ clipPath: 'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)' }}></div>
        </div>
        <div className="absolute bottom-0 left-0 right-0">
          <div className="overflow-hidden h-1/2">
            {/* Replace this inline SVG */}
            {/* <svg ...> ... </svg> */}

            {/* With an <img> tag pointing to the SVG file */}
            {/* <img src="Rubbish_Border_Standard.svg" alt="Complex Shape Divider" /> */}
          </div>
        </div>
        <div className="mx-auto max-w-7xl px-6 lg:px-8 flex justify-between items-center z-10 pt-20">
          <div className="max-w-2xl">
            <h2 className="text-4xl font-bold tracking-tight text-white sm:text-6xl">About Us</h2>
            <p className="mt-6 pb-10 text-lg leading-8 text-white opacity-70">Here at Rubbish Ideas, we proudly champion the principles of the circular economy, with a keen focus on closed capture venues. Born from our roots, the Rubbish Portal harmoniously blends our circularity consultancy with state-of-the-art material tracking systems, cultivated through our impactful work in the events industry. </p>
            <div className="mx-auto mt-10 max-w-2xl lg:mx-0 lg:max-w-none pb-14">
              <div className="grid grid-cols-1 gap-x-8 gap-y-6 text-base font-semibold leading-7 text-white sm:grid-cols-2 md:flex lg:gap-x-10">
                <a className="hover:scale-105 animation duration-1000" href="#our-commitment">Our commitment <span aria-hidden="true">&rarr;</span></a>
                <a className="hover:scale-105 animation duration-1000" href="#about">Who we are <span aria-hidden="true">&rarr;</span></a>
                <a className="hover:scale-105 animation duration-1000" href="#features">Key features & benefits <span aria-hidden="true">&rarr;</span></a>
              </div>
            </div>
          </div>

          {/* New div for the image */}
          {/* <div className="flex-1 hidden p-8 lg:block object-center -z-10 animate-fade-in">
            <div className='flex items-center relative top-0 bottom-0 pl-20 pb-20 w-400 h-400'>
              <img className="block absolute animate-rotate" src="Service_Animation-11.png" alt="Recycle" />
              <img className="block absolute animate-poptwo" src="Service_Animation-10.png" alt="Trees" />
              <img className="block absolute animate-popone" src="Service_Animation-09.png" alt="Waste" />
            </div>
          </div> */}
        </div>
      </div>

      <div className="relative isolate overflow-hidden bg-white px-6 py-24 sm:py-32 lg:overflow-visible lg:px-0">
        <div className="absolute inset-0 -z-10 overflow-hidden">
        </div>
        <div className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 lg:mx-0 lg:max-w-none lg:grid-cols-2 lg:items-start lg:gap-y-10">
          <div className="lg:col-span-2 lg:col-start-1 lg:row-start-1 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className="lg:max-w-lg">
                <p id="our-commitment" className="text-base font-semibold leading-7 text-indigo-600">Mission Rubbish</p>
                <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Our Commitment</h1>
                <p className="mt-6 text-xl leading-8 text-gray-700">At Rubbish Ideas, our commitment to driving circularity extends beyond technology development.</p>
              </div>
            </div>
          </div>
          <div className="-ml-12 -mt-12 p-12 pb-0 lg:sticky lg:top-4 lg:col-start-2 lg:row-span-2 lg:row-start-1 lg:overflow-hidden">
            <SlideInImage imageUrl="/Full_Logo.svg" />
            <div className="flex justify-center mt-10 ">
              <a className="btn flex text-center mx-10 rounded-xl bg-tertiary p-4 text-white hover:bg-navy animate duration-500 sm:ml-4 sm:w-auto" href="/#subscribe">
                Join our mission
              </a>
            </div>
          </div>
          <div className="lg:col-span-2 lg:col-start-1 lg:row-start-2 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className="max-w-xl text-base leading-7 text-gray-700 lg:max-w-lg">
                <p>Over the years, we have established ourselves as trusted partners in the events industry, collaborating with major international breweries like ABInBev and Heineken, as well as event companies. Together, we have implemented closed-loop recycling systems for rPET cups, diverting significant amounts of waste from landfills.</p>
                <p className='mt-4'>Through these initiatives, we not only address the immediate waste challenges faced by the events community but also foster a culture of sustainability. We believe that by working together with organisations and event organisers, we can create a significant and lasting impact on the journey towards a waste-free future.</p>
                <h2 className="mt-16 text-2xl font-bold tracking-tight text-gray-900">Join our mission.</h2>
                <p className="mt-6">We want to transform the events industry into a beacon of sustainability. Together, with The Rubbish Portal as a powerful tool, we can drive change, improve recycling rates, and contribute to a cleaner, greener planet for generations to come.</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="relative isolate overflow-hidden bg-white px-6 py-24 sm:py-32 lg:overflow-visible lg:px-0">
        <div className="absolute inset-0 -z-10 overflow-hidden">
          <svg className="absolute left-[max(50%,25rem)] top-0 h-[64rem] w-[128rem] -translate-x-1/2 stroke-gray-200 [mask-image:radial-gradient(64rem_64rem_at_top,white,transparent)]" aria-hidden="true">
            <defs>
              <pattern id="e813992c-7d03-4cc4-a2bd-151760b470a0" width="200" height="200" x="50%" y="-1" patternUnits="userSpaceOnUse">
                <path d="M100 200V.5M.5 .5H200" fill="none" />
              </pattern>
            </defs>
            <svg x="50%" y="-1" className="overflow-visible fill-gray-50">
              <path d="M-100.5 0h201v201h-201Z M699.5 0h201v201h-201Z M499.5 400h201v201h-201Z M-300.5 600h201v201h-201Z" stroke-width="0" />
            </svg>
            <rect width="100%" height="100%" stroke-width="0" fill="url(#e813992c-7d03-4cc4-a2bd-151760b470a0)" />
          </svg>
        </div>
        <div className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 lg:mx-0 lg:max-w-none lg:grid-cols-2 lg:items-start lg:gap-y-10">
          <div className="lg:col-span-2 lg:col-start-1 lg:row-start-1 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className="lg:max-w-lg">
                <p id="about" className="text-base font-semibold leading-7 text-indigo-600">Who are we?</p>
                <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">About The Rubbish Portal</h1>
                <p className="mt-6 text-xl leading-8 text-gray-700">Welcome to The Rubbish Portal, an innovative waste tracking software developed by Rubbish Ideas, a leading circular economy design consultancy based in the United Kingdom.</p>

              </div>
            </div>
          </div>
          <div className="-ml-12 -mt-12 p-12 pb-0 lg:sticky lg:top-4 lg:col-start-2 lg:row-span-2 lg:row-start-1 lg:overflow-hidden">
            <SlideInImage imageUrl="/Full_Logo.svg" hasShadow={false} />
            <div className="flex justify-center mt-10">
              <a
                className="btn flex text-center mx-10 rounded-xl bg-tertiary p-4 text-white hover:bg-navy transition-transform duration-500 sm:ml-4 sm:w-auto"
                href="https://rubbish-ideas.com"
              >
                See Rubbish Ideas
              </a>
            </div>
          </div>
          <div className="lg:col-span-2 lg:col-start-1 lg:row-start-2 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className="max-w-xl text-base leading-7 text-gray-700 lg:max-w-lg">
                <p>At Rubbish Ideas, we are dedicated to realizing a waste-free future and empowering organizations to embrace circular practices across their operations. Our expertise spans various industries, with a remarkable impact in the events sector.</p>
                <p className='mt-4'>The Rubbish Portal is one of our key achievements and offerings—a groundbreaking SaaS platform designed to address the emerging challenge of effectively managing waste and recycling at events. As the events industry continues to grow, so does the need for sustainable waste management solutions. The Rubbish Portal steps up to the challenge by serving as an online tracker, collecting and reporting recycling data for events and their stakeholders.</p>
                <p className='mt-4'>Our mission with The Rubbish Portal is to harness the power of data and analytics to create specific and tailored performance metrics. By doing so, we empower event organizers to make informed decisions and drive continuous improvement towards more sustainable practices. We firmly believe that sustainability outcomes are crucial for our planet's future, and The Rubbish Portal plays a vital role in achieving this goal.</p>
                <h2 className="mt-16 text-2xl font-bold tracking-tight text-gray-900">Interested?</h2>
                <p className="mt-6">Send us an email and we would be happy to arrange a demo of the software, and discuss your specific requirements.</p>
              </div>
            </div>
          </div>
        </div>
      </div>


      <div className="relative isolate overflow-hidden bg-white px-6 py-24 sm:py-32 lg:overflow-visible lg:px-0">
        <div className="absolute inset-0 -z-10 overflow-hidden">
        </div>
        <div className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 lg:mx-0 lg:max-w-none lg:grid-cols-2 lg:items-start lg:gap-y-10">
          <div className="lg:col-span-2 lg:col-start-1 lg:row-start-1 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className="lg:max-w-lg">
                <p id="features" className="text-base font-semibold leading-7 text-indigo-600">Why choose The Rubbish Portal?</p>
                <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl"> Key Features & Benefits</h1>
                <p className="mt-6 text-xl leading-8 text-gray-700">Track recycling performance at events in real-time, compare and rank results for healthy competition and improvement, and receive actionable recommendations to optimize recycling rates and create a sustainable future.</p>
              </div>
            </div>
          </div>

          <div className="-ml-12 -mt-12 p-12 pb-0 lg:sticky lg:top-4 lg:col-start-2 lg:row-span-2 lg:row-start-1 lg:overflow-hidden">
            <SlideInImage imageUrl="/Full_Logo.svg" />
            <div className="flex justify-center mt-10">
              <a
                className="btn flex text-center mx-10 rounded-xl bg-tertiary p-4 text-white hover:bg-navy transition-transform duration-500 sm:ml-4 sm:w-auto"
                href="/?demo=true#demo"
              >
                Book a Demo
              </a>
            </div>
          </div>


          <div className="lg:col-span-2 lg:col-start-1 lg:row-start-2 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className="max-w-xl text-base leading-7 text-gray-700 lg:max-w-lg">
                <ul role="list" className="mt-8 space-y-8 text-gray-600">
                  <li className="flex gap-x-3">
                    <svg className="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M5.5 17a4.5 4.5 0 01-1.44-8.765 4.5 4.5 0 018.302-3.046 3.5 3.5 0 014.504 4.272A4 4 0 0115 17H5.5zm3.75-2.75a.75.75 0 001.5 0V9.66l1.95 2.1a.75.75 0 101.1-1.02l-3.25-3.5a.75.75 0 00-1.1 0l-3.25 3.5a.75.75 0 101.1 1.02l1.95-2.1v4.59z" clip-rule="evenodd" />
                    </svg>
                    <span><strong className="font-semibold text-gray-900">Recycling Performance Tracking</strong> The Rubbish Portal measures and tracks recycling performance at events, providing real-time insights into waste management efforts. This data-driven approach enables organisers to identify strengths and weaknesses in their recycling programs.</span>
                  </li>
                  <li className="flex gap-x-3">
                    <svg className="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M10 1a4.5 4.5 0 00-4.5 4.5V9H5a2 2 0 00-2 2v6a2 2 0 002 2h10a2 2 0 002-2v-6a2 2 0 00-2-2h-.5V5.5A4.5 4.5 0 0010 1zm3 8V5.5a3 3 0 10-6 0V9h6z" clip-rule="evenodd" />
                    </svg>
                    <span><strong className="font-semibold text-gray-900">Comparison & Ranking</strong> Our platform goes beyond simple tracking and offers the ability to compare and rank events based on their recycling results. This feature facilitates healthy competition among event organisers and encourages them to improve their recycling efforts continually.</span>
                  </li>
                  <li className="flex gap-x-3">
                    <svg className="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path d="M4.632 3.533A2 2 0 016.577 2h6.846a2 2 0 011.945 1.533l1.976 8.234A3.489 3.489 0 0016 11.5H4c-.476 0-.93.095-1.344.267l1.976-8.234z" />
                      <path fill-rule="evenodd" d="M4 13a2 2 0 100 4h12a2 2 0 100-4H4zm11.24 2a.75.75 0 01.75-.75H16a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75h-.01a.75.75 0 01-.75-.75V15zm-2.25-.75a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75H13a.75.75 0 00.75-.75V15a.75.75 0 00-.75-.75h-.01z" clip-rule="evenodd" />
                    </svg>
                    <span><strong className="font-semibold text-gray-900">Actionable Recommendations</strong> The Rubbish Portal offers actionable recommendations based on the collected data. These insights help event organisers make informed decisions and design effective waste management systems that optimise recycling rates.</span>
                  </li>
                  <li className="flex gap-x-3">
                    <svg className="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path d="M4.632 3.533A2 2 0 016.577 2h6.846a2 2 0 011.945 1.533l1.976 8.234A3.489 3.489 0 0016 11.5H4c-.476 0-.93.095-1.344.267l1.976-8.234z" />
                      <path fill-rule="evenodd" d="M4 13a2 2 0 100 4h12a2 2 0 100-4H4zm11.24 2a.75.75 0 01.75-.75H16a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75h-.01a.75.75 0 01-.75-.75V15zm-2.25-.75a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75H13a.75.75 0 00.75-.75V15a.75.75 0 00-.75-.75h-.01z" clip-rule="evenodd" />
                    </svg>
                    <span><strong className="font-semibold text-gray-900">Contribution to a Sustainable Future</strong> With a strong focus on reducing carbon emissions and minimising waste volume, The Rubbish Portal targets a minimum recycling rate of 75%. By using the platform, event organisers actively contribute to a more sustainable future.</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>


      <Footer />
    </>
  );
}