import React from 'react';
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "../components/header"

const About: NextPage = () => {
    return (
        <>
            <Head>
                <title>Macrovesta</title>
                <meta name="description" content="Generated by Macrovesta" />
                <link rel="icon" href="/favicon.ico" />
                {/* <script src="/static/datafeeds/udf/dist/bundle.js" async /> */}
                <link rel="alternate" hrefLang="en" href="https://www.macrovesta.ai" />
                <link rel="alternate" hrefLang="pt-br" href="https://pt-br.macrovesta.ai" />
                <link rel="alternate" hrefLang="es" href="https://es.macrovesta.ai" />
                <link rel="alternate" hrefLang="tr" href="https://tr.macrovesta.ai" />
                <link rel="alternate" hrefLang="th" href="https://th.macrovesta.ai" />
                {/* <script type="text/javascript" src="https://cdn.weglot.com/weglot.min.js"></script>
        <script>
          {Weglot.initialize({
            api_key: 'wg_60b49229f516dee77edb3109e6a46c379'
          })}
        </script> */}
            </Head>
            <main>
                <Header />
            </main>
        </>
    )
}

export default About