import React, { useEffect, useState, useRef } from 'react'
import Header from '../components/header'
import Footer from '../components/footer'
import SlideInImage from '../components/slideInImage'
import CookieConsent from '../components/cookieConsent'
import { getSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

export const metadata = {
  title: 'About',
  description: 'Learn more about The Rubbish Portal'
}

export default function About () {
  return (
    <>
      <Head>
        <title>Macrovesta</title>
        <meta name="description" content="Generated by Macrovesta" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="/static/datafeeds/udf/dist/bundle.js" async /> */}
        <link rel="alternate" hrefLang="en" href="https://www.macrovesta.ai" />
        <link rel="alternate" hrefLang="pt-br" href="https://pt-br.macrovesta.ai" />
        <link rel="alternate" hrefLang="es" href="https://es.macrovesta.ai" />
        <link rel="alternate" hrefLang="tr" href="https://tr.macrovesta.ai" />
        <link rel="alternate" hrefLang="th" href="https://th.macrovesta.ai" />
        {/* <script type="text/javascript" src="https://cdn.weglot.com/weglot.min.js"></script>
        <script>
          {Weglot.initialize({
            api_key: 'wg_60b49229f516dee77edb3109e6a46c379'
          })}
        </script> */}
      </Head>
      <Header />
      <CookieConsent />
      <div className="animate-slidedown relative isolate overflow-hidden bg-gradient-to-tr from-deep_blue to-navy py-24 sm:py-32">
        <div className="hidden sm:absolute sm:-top-10 sm:right-1/2 sm:-z-10 sm:mr-10 sm:block sm:transform-gpu sm:blur-3xl animate-expand" aria-hidden="true">
          <div className="aspect-[1097/845] w-[68.5625rem] bg-gradient-to-tr  from-navy to-deep_blue opacity-30" style={{ clipPath: 'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)' }}></div>
        </div>
        <div className="absolute -top-52 left-1/2 -z-10 -translate-x-1/2 transform-gpu blur-3xl sm:top-[-28rem] sm:ml-16 sm:translate-x-0 sm:transform-gpu animate-expand" aria-hidden="true">
          <div className="aspect-[1097/845] w-[68.5625rem] bg-gradient-to-tr  from-navy to-deep_blue opacity-30" style={{ clipPath: 'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)' }}></div>
        </div>
        <div className="absolute bottom-0 left-0 right-0">
          <div className="overflow-hidden h-1/2">
            {/* Replace this inline SVG */}
            {/* <svg ...> ... </svg> */}

            {/* With an <img> tag pointing to the SVG file */}
            {/* <img src="Rubbish_Border_Standard.svg" alt="Complex Shape Divider" /> */}
          </div>
        </div>
        <div className="mx-auto max-w-7xl px-6 lg:px-8 flex justify-between items-center z-10 pt-20">
          <div className="max-w-2xl">
            <h2 className="text-4xl font-bold tracking-tight text-white sm:text-6xl">About Us</h2>
            <p className="mt-6 pb-10 text-lg leading-8 text-white opacity-70">Market prediction science is a growing Artificial Intelligence (AI) field. Yet, while current technology offers impressive data processing and pattern recognition power, it still lacks specific market expertise.<br /><br />

              Macrovesta has teamed up with a leading UK University to unite acute market awareness with advanced AI for highly specialised market prediction and analysis. Using cutting-edge AI methods, we are continuously testing and improving our existing mathematical models, which have been used effectively by our expert analysts for well over a decade.<br /><br />

              This is the future of commodity analysis. </p>
            <div className="mx-auto mt-10 max-w-2xl lg:mx-0 lg:max-w-none pb-14">
              <div className="grid grid-cols-1 gap-x-8 gap-y-6 text-base font-semibold leading-7 text-white sm:grid-cols-2 md:flex lg:gap-x-10">
                <a className="hover:scale-105 animation duration-1000" href="#our-story">Our story <span aria-hidden="true">&rarr;</span></a>
                <a className="hover:scale-105 animation duration-1000" href="#team">Meet our team <span aria-hidden="true">&rarr;</span></a>
                <a className="hover:scale-105 animation duration-1000" href="#mission">Our mission <span aria-hidden="true">&rarr;</span></a>
              </div>
            </div>
          </div>

          {/* New div for the image */}
          <div className="flex-1 hidden px-4 -mr-16 xl:-mr-28 lg:block object-center -z-10">
            <div className='flex items-center relative top-0 bottom-0  pb-20 w-full min-w-[450px] xl:w-full h-full min-h-[450px] xl:h-full'>
              <img className="block" src="Isometric Macrovesta Images_AI Market Prediction.png" alt="Recycle" />
              {/* <img className="block absolute animate-poptwo" src="Service_Animation-10.png" alt="Trees" />
              <img className="block absolute animate-popone" src="Service_Animation-09.png" alt="Waste" /> */}
            </div>
          </div>
        </div>
      </div>

      <div className="relative isolate overflow-hidden bg-white px-6 py-12 sm:py-12 lg:overflow-visible lg:px-0">
        <div className="absolute inset-0 -z-10 overflow-hidden">
        </div>
        <div className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 lg:mx-0 lg:max-w-none lg:grid-cols-2 lg:items-start lg:gap-y-10">
          <div className="lg:col-span-2 lg:col-start-1 lg:row-start-1 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className="lg:max-w-lg">
                {/* <p id="our-story" className="text-base font-semibold leading-7 text-indigo-600">Mission Rubbish</p> */}
                {/* <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Our Story</h1> */}
                {/* <p className="mt-6 text-xl leading-8 text-gray-700">At Rubbish Ideas, our commitment to driving circularity extends beyond technology development.</p> */}
              </div>
            </div>
          </div>
          <div className="-ml-12 -mt-12 p-12 pb-0 lg:sticky lg:top-4 lg:col-start-2 lg:row-span-2 lg:row-start-1 lg:overflow-hidden">
            <SlideInImage hasShadow={false} imageUrl="/Isometric Macrovesta Images_Farm.png" />
            <div className="flex justify-center mt-10 ">
              <a className="btn flex text-center mx-10 rounded-xl bg-deep_blue p-4 text-white hover:bg-navy animate duration-500 sm:ml-4 sm:w-auto" href="/#subscribe">
                Become a pilot client
              </a>
            </div>
          </div>
          <div className="lg:col-span-2 lg:col-start-1 lg:row-start-2 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className="max-w-xl text-base leading-7 text-gray-700 lg:max-w-lg">
                <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl mb-8">Our Story</h1>

                <p>The global commodities market needs a scalable approach to risk management and hedging strategies. 10 years ago our analysts have provided these services to a small group of large players in across the global cotton supply chain.<br /><br /> In 2021, our analysts met with leading software and Artificial Intelligence technologists to strategise how their services could be scaled to help the wider market. Together we identified the opportunity to leverage market-leading expertise and services through software backed by Artificial Intelligence rather than traditional consultancy methods. Thus overcoming the physical limitations that have previously prevented scalability, despite reliable and in-demand services.</p>
                {/* <p className='mt-4'>Through these initiatives, we not only address the immediate waste challenges faced by the events community but also foster a culture of sustainability. We believe that by working together with organisations and event organisers, we can create a significant and lasting impact on the journey towards a waste-free future.</p>
                <h2 className="mt-16 text-2xl font-bold tracking-tight text-gray-900">Join our mission.</h2>
                <p className="mt-6">We want to transform the events industry into a beacon of sustainability. Together, with The Rubbish Portal as a powerful tool, we can drive change, improve recycling rates, and contribute to a cleaner, greener planet for generations to come.</p> */}
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="relative isolate overflow-hidden bg-white px-6 py-12 sm:py-12 lg:overflow-visible lg:px-0">
        {/* <div className="absolute inset-0 -z-10 overflow-hidden">
          <svg className="absolute left-[max(50%,25rem)] top-0 h-[64rem] w-[128rem] -translate-x-1/2 stroke-gray-200 [mask-image:radial-gradient(64rem_64rem_at_top,white,transparent)]" aria-hidden="true">
            <defs>
              <pattern id="e813992c-7d03-4cc4-a2bd-151760b470a0" width="200" height="200" x="50%" y="-1" patternUnits="userSpaceOnUse">
                <path d="M100 200V.5M.5 .5H200" fill="none" />
              </pattern>
            </defs>
            <svg x="50%" y="-1" className="overflow-visible fill-gray-50">
              <path d="M-100.5 0h201v201h-201Z M699.5 0h201v201h-201Z M499.5 400h201v201h-201Z M-300.5 600h201v201h-201Z" stroke-width="0" />
            </svg>
            <rect width="100%" height="100%" stroke-width="0" fill="url(#e813992c-7d03-4cc4-a2bd-151760b470a0)" />
          </svg>
        </div> */}
        <div className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 lg:mx-0 lg:max-w-none lg:items-start lg:gap-y-10">
          <div className='mx-auto'>
            <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-4 py-12">
              <div className="text-center pb-12">
                {/* <h2 className="text-base font-bold text-indigo-600">
                  We have the best equipment
                </h2> */}
                <h1 className="font-bold text-3xl md:text-4xl lg:text-5xl font-heading text-gray-900">
                  Meet our team
                </h1>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-2">
                <div className="w-full bg-white rounded-lg p-4 flex flex-col justify-start items-center">
                  <div className="mb-8">
                    <Image style={{ objectPosition: 'center', objectFit: 'cover', borderRadius: '9999px', height: '144px' }} width={144} height={144} src={'/JE.jpeg'} alt='Jo Earlam Profile' />
                    {/* <img className="object-center object-cover rounded-full h-36 w-36" src="/JE.jpeg" alt="photo" /> */}
                  </div>
                  <div className="text-center">
                    <p className="text-xl text-gray-700 font-bold mb-2">Jo Earlam</p>
                    <p className="text-base text-gray-400 font-normal">Chairman & Advisor</p>
                    <p className='text-[14px] text-gray-500'>Jo set up his commodity consultancy business in 2009, having previously worked as a stockbroker dealer in the City of London. Jo has long advocated that fundamentals, technicals, and money flow are all essential ingredients in determining future price direction. A lifetime of working with futures and options has given him a sound understanding of markets as a whole.</p>
                  </div>
                </div>
                <div className="w-full bg-white rounded-lg p-4 flex flex-col justify-start items-center">
                  <div className="mb-8">
                    <Image style={{ objectPosition: 'center', objectFit: 'cover', borderRadius: '9999px', height: '144px' }} width={144} height={144} src={'/Olly.jpeg'} alt='Oliver Jobling Profile' />
                    {/* <img className="object-center object-cover rounded-full h-36 w-36" src="/Olly.jpeg" alt="photo" /> */}
                  </div>
                  <div className="text-center">
                    <p className="text-xl text-gray-700 font-bold mb-2">Oliver Jobling</p>
                    <p className="text-base text-gray-400 font-normal">Managing Director</p>
                    <p className='text-[14px] text-gray-500'>Since completing his masters degree in Innovative Manufacturing Engineering in 2017, Oliver has worked in communications and software development, focusing on the use of scalable technology to strengthen communication channels. </p>
                  </div>
                </div>
                <div className="w-full bg-white rounded-lg p-4 flex flex-col justify-start items-center">
                  <div className="mb-8">
                    <Image style={{ objectPosition: 'center', objectFit: 'cover', borderRadius: '9999px', height: '144px' }} width={144} height={144} src={'/Nafisah Badmos.jpeg'} alt='Nafisah Badmos Profile' />
                    {/* <img className="object-center object-cover rounded-full h-36 w-36" src="/Nafisah Badmos.jpeg" alt="photo" /> */}
                  </div>
                  <div className="text-center">
                    <p className="text-xl text-gray-700 font-bold mb-2">Nafisah Badmos</p>
                    <p className="text-base text-gray-400 font-normal">Data Science Lead</p>
                    <p className='text-[14px] text-gray-500'>With a master's degree in data science and a wealth of industrial experience in artificial intelligence, Nafisah joined Macrovesta with an impressive record of solving complex problems with AI.</p>

                  </div>
                </div>
                <div className="w-full bg-white rounded-lg p-4 flex flex-col justify-start items-center">
                  <div className="mb-8">
                    <Image style={{ objectPosition: 'center', objectFit: 'cover', borderRadius: '9999px', height: '144px' }} width={144} height={144} src={'/Vic.jpeg'} alt='Victor Fernandes Profile' />
                    {/* <img className="object-center object-cover rounded-full h-36 w-36" src="Vic.jpeg" alt="photo" /> */}
                  </div>
                  <div className="text-center">
                    <p className="text-xl text-gray-700 font-bold mb-2">Victor Fernandes</p>
                    <p className="text-base text-gray-400 font-normal">Software Development Lead</p>
                    <p className='text-[14px] text-gray-500'>Victor joined Macrovesta with extensive web design and development experience after finishing his studies in America. He continues to grow Macrovesta's consultancy business to Portuguese and Spanish speaking countries and is being introduce to all aspects of cotton trading to improve the development for the entire cotton supply chain.</p>

                  </div>
                </div>
                <div className="w-full bg-white rounded-lg p-4 flex flex-col justify-start items-center">
                  <div className="mb-8">
                    <Image style={{ objectPosition: 'center', objectFit: 'cover', borderRadius: '9999px', height: '144px' }} width={144} height={144} src={'/default-avatar-icon-of-social-media-user-vector.jpeg'} alt='Gary Ferguson Profile' />
                    {/* <img className="object-center object-cover rounded-full h-36 w-36" src="/default-avatar-icon-of-social-media-user-vector.jpeg" alt="photo" /> */}
                  </div>
                  <div className="text-center">
                    <p className="text-xl text-gray-700 font-bold mb-2">Gary Ferguson</p>
                    <p className="text-base text-gray-400 font-normal">Chief Financial Officer</p>
                    <p className='text-[14px] text-gray-500'>Gary is a fully qualified CIMA accountant with over 25 years of commodity experience with specific focus on merchant accounting, treasury/ facility management and statistical market analysis. He developed the first version of the Macrovesta Market Prediction Database over a decade ago and has been integral to the 3 iterations that have followed. </p>

                  </div>
                </div>
                <div className="w-full bg-white rounded-lg p-4 flex flex-col justify-start items-center">
                  <div className="mb-8">
                    <Image style={{ objectPosition: 'center', objectFit: 'cover', borderRadius: '9999px', height: '144px' }} width={144} height={144} src={'/NJB.jpg'} alt='Nick Brice Profile' />
                    {/* <img className="object-center object-cover rounded-full h-36 w-36" src="/NJB.jpg" alt="photo" /> */}
                  </div>
                  <div className="text-center">
                    <p className="text-xl text-gray-700 font-bold mb-2">Nick Brice</p>
                    <p className="text-base text-gray-400 font-normal">Software Developer</p>
                    <p className='text-[14px] text-gray-500'>Nick’s pragmatic approach to technical problem solving has made him an invaluable addition to the Macrovesta software development team since joining the team.</p>

                  </div>
                </div>
                <div className="w-full bg-white rounded-lg p-4 flex flex-col justify-start items-center">
                  <div className="mb-8">
                    <Image style={{ objectPosition: 'center', objectFit: 'cover', borderRadius: '9999px', height: '144px' }} width={144} height={144} src={'/default-avatar-icon-of-social-media-user-vector.jpeg'} alt='Chris Williams Profile' />
                    {/* <img className="object-center object-cover rounded-full h-36 w-36" src="/default-avatar-icon-of-social-media-user-vector.jpeg" alt="photo" /> */}
                  </div>
                  <div className="text-center">
                    <p className="text-xl text-gray-700 font-bold mb-2">Chris Williams</p>
                    <p className="text-base text-gray-400 font-normal">Commodity Consultant</p>
                    <p className='text-[14px] text-gray-500'>Chris worked for Cargill Cotton for 11 years joining in Shanghai, China. After returning to the UK Chris worked Shanghai, China. After returning to the UK Chris worked as a trader managing a number of consuming markets and sourcing originations around the globe.</p>

                  </div>
                </div>
                <div className="w-full bg-white rounded-lg p-4 flex flex-col justify-start items-center">
                  <div className="mb-8">
                    <Image style={{ objectPosition: 'center', objectFit: 'cover', borderRadius: '9999px', height: '144px' }} width={144} height={144} src={'/HWB.jpeg'} alt='Harry Bennett Profile' />
                    {/* <img className="object-center object-cover rounded-full h-36 w-36" src="/HWB.jpeg" alt="photo" /> */}
                  </div>
                  <div className="text-center">
                    <p className="text-xl text-gray-700 font-bold mb-2">Harry Bennett</p>
                    <p className="text-base text-gray-400 font-normal">Commodity Consultant</p>
                    <p className='text-[14px] text-gray-500'>Harry joined EAP in 2017, having previously worked for a wealth management firm in Hong Kong. Harry is a qualified cotton broker and Civil Engineer.</p>

                  </div>
                </div>
                <div className="w-full bg-white rounded-lg p-4 flex flex-col justify-start items-center">
                  <div className="mb-8">
                    <Image style={{ objectPosition: 'center', objectFit: 'cover', borderRadius: '9999px', height: '144px' }} width={144} height={144} src={'/BW.jpeg'} alt='Ben Williams Profile' />
                    {/* <img className="object-center object-cover rounded-full h-36 w-36" src="/BW.jpeg" alt="photo" /> */}
                  </div>
                  <div className="text-center">
                    <p className="text-xl text-gray-700 font-bold mb-2">Ben Williams</p>
                    <p className="text-base text-gray-400 font-normal">Commodity Consultant</p>
                    <p className='text-[14px] text-gray-500'>Having previously worked in logistics for a food ingredients trading company, importing and exporting products all around the globe, he comes with an in depth knowledge of shipping and the administration.</p>

                  </div>
                </div>
                <div className="w-full bg-white rounded-lg p-4 flex flex-col justify-start items-center">
                  <div className="mb-8">
                    <Image style={{ objectPosition: 'center', objectFit: 'cover', borderRadius: '9999px', height: '144px' }} width={144} height={144} src={'/simone_profile.jpg'} alt='Simone Massardi Profile' />
                    {/* <img className="object-center object-cover rounded-full h-36 w-36" src="/BW.jpeg" alt="photo" /> */}
                  </div>
                  <div className="text-center">
                    <p className="text-xl text-gray-700 font-bold mb-2">Simone Massardi</p>
                    <p className="text-base text-gray-400 font-normal">Junior Data Scientist</p>
                    <p className='text-[14px] text-gray-500'>Simone grew up with a deep passion for science and mathematics, which led him to earn a degree in mathematics and a Master's in Data Science from the University of Milan. During his time there, he developed a strong interest in creating and optimizing predictive models and finding value within data.</p>

                  </div>
                </div>
                <div className="w-full bg-white rounded-lg p-4 flex flex-col justify-start items-center">
                  <div className="mb-8">
                    <Image style={{ objectPosition: 'center', objectFit: 'cover', borderRadius: '9999px', height: '144px' }} width={144} height={144} src={'/nick_profile.jpg'} alt='Nick Newns Profile' />
                    {/* <img className="object-center object-cover rounded-full h-36 w-36" src="/BW.jpeg" alt="photo" /> */}
                  </div>
                  <div className="text-center">
                    <p className="text-xl text-gray-700 font-bold mb-2">Nick Newns</p>
                    <p className="text-base text-gray-400 font-normal">Commodity Consultant</p>
                    <p className='text-[14px] text-gray-500'>Nick has been involved in the cotton and textile industries for nearly 25 years, trading raw cotton for Liverpool cotton merchant and then relocating to Singapore to run a sales desk concentrating on managing customers requirements in the South East Asian and Indian Subcontinent markets.</p>

                  </div>
                </div>
              </div>
            </section>
          </div>
          {/* <div className="lg:col-span-2 lg:col-start-1 lg:row-start-1 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className="lg:max-w-lg">
                <p id="team" className="text-base font-semibold leading-7 text-indigo-600">Who are we?</p>
                <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">About The Rubbish Portal</h1>
                <p className="mt-6 text-xl leading-8 text-gray-700">Welcome to The Rubbish Portal, an innovative waste tracking software developed by Rubbish Ideas, a leading circular economy design consultancy based in the United Kingdom.</p>

              </div>
            </div>
          </div>
          <div className="-ml-12 -mt-12 p-12 pb-0 lg:sticky lg:top-4 lg:col-start-2 lg:row-span-2 lg:row-start-1 lg:overflow-hidden">
            <SlideInImage imageUrl="/Full_Logo.svg" hasShadow={false} />
            <div className="flex justify-center mt-10">
              <a
                className="btn flex text-center mx-10 rounded-xl bg-tertiary p-4 text-white hover:bg-navy transition-transform duration-500 sm:ml-4 sm:w-auto"
                href="https://rubbish-ideas.com"
              >
                See Rubbish Ideas
              </a>
            </div>
          </div> */}
          {/* <div className="lg:col-span-2 lg:col-start-1 lg:row-start-2 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className="max-w-xl text-base leading-7 text-gray-700 lg:max-w-lg">
                <p>At Rubbish Ideas, we are dedicated to realizing a waste-free future and empowering organizations to embrace circular practices across their operations. Our expertise spans various industries, with a remarkable impact in the events sector.</p>
                <p className='mt-4'>The Rubbish Portal is one of our key achievements and offerings—a groundbreaking SaaS platform designed to address the emerging challenge of effectively managing waste and recycling at events. As the events industry continues to grow, so does the need for sustainable waste management solutions. The Rubbish Portal steps up to the challenge by serving as an online tracker, collecting and reporting recycling data for events and their stakeholders.</p>
                <p className='mt-4'>Our mission with The Rubbish Portal is to harness the power of data and analytics to create specific and tailored performance metrics. By doing so, we empower event organizers to make informed decisions and drive continuous improvement towards more sustainable practices. We firmly believe that sustainability outcomes are crucial for our planet's future, and The Rubbish Portal plays a vital role in achieving this goal.</p>
                <h2 className="mt-16 text-2xl font-bold tracking-tight text-gray-900">Interested?</h2>
                <p className="mt-6">Send us an email and we would be happy to arrange a demo of the software, and discuss your specific requirements.</p>
              </div>
            </div>
          </div> */}
        </div>
      </div>

      <div className="relative isolate overflow-hidden bg-white px-6 py-12 sm:py-12 lg:overflow-visible lg:px-0">
        <div className="absolute inset-0 -z-10 overflow-hidden">
        </div>
        <div className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 lg:mx-0 lg:max-w-none lg:grid-cols-2 lg:items-start lg:gap-y-10">
          <div className="lg:col-span-2 lg:col-start-1 lg:row-start-1 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className="lg:max-w-lg">
                {/* <p id="mission" className="text-base font-semibold leading-7 text-indigo-600">Why choose The Rubbish Portal?</p> */}
                {/* <h1 id="mission" className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl"> Our mission</h1> */}
                {/* <p className="mt-6 text-xl leading-8 text-gray-700">Track recycling performance at events in real-time, compare and rank results for healthy competition and improvement, and receive actionable recommendations to optimize recycling rates and create a sustainable future.</p> */}
              </div>
            </div>
          </div>

          <div className="-ml-12 -mt-12 p-12 pb-0 lg:sticky lg:top-4 lg:col-start-2 lg:row-span-2 lg:row-start-1 lg:overflow-hidden">
            <SlideInImage hasShadow={false} imageUrl="/Isometric Macrovesta Images_Multilingual.png" />
            <div className="flex justify-center mt-10">
              <a
                className="btn flex text-center mx-10 rounded-xl bg-deep_blue p-4 text-white hover:bg-navy transition-transform duration-500 sm:ml-4 sm:w-auto"
                href="/introduction?demo=true#demo"
              >
                Book a Demo
              </a>
            </div>
          </div>

          <div className="lg:col-span-2 lg:col-start-1 lg:row-start-2 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className="max-w-xl text-base leading-7 text-gray-700 lg:max-w-lg">
                <h1 id="mission" className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl mb-8"> Our mission</h1>

                <p className="mt-6 text-xl leading-8 text-gray-700">To educate and assist farmers, processors, merchants and retailers in understanding the agricultural commodity markets, providing guidance on navigating global price fluctuations and minimising any negative impacts on their business. To do this Macrovesta is displaying data and insights from our Commodity Price Prediction system - a lightweight and explainable AI technology. This tool enhances market understanding and facilitates informed decision-making that affects the livelihood of agricultural professionals around the world.<br /><br />

                  In 2022, The World Bank and the US Treasury expressed concerns over increasing commodity market volatility and shortened seasons, which will have profound implications for developing countries over the coming decade. A more resilient supply chain for agricultural commodities can have a momentous impact on developing countries across the globe. Providing them with actionable insights is a crucial step towards achieving this goal.<br /><br />

                  Our digital platform enables organisations of any size to gain access to real-time market insights and forecasts. The platform leverages databases compiled over decades of research and analysis as well as new information derived from predictive technology. </p>

                {/* <ul role="list" className="mt-8 space-y-8 text-gray-600">
                  <li className="flex gap-x-3">
                    <svg className="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M5.5 17a4.5 4.5 0 01-1.44-8.765 4.5 4.5 0 018.302-3.046 3.5 3.5 0 014.504 4.272A4 4 0 0115 17H5.5zm3.75-2.75a.75.75 0 001.5 0V9.66l1.95 2.1a.75.75 0 101.1-1.02l-3.25-3.5a.75.75 0 00-1.1 0l-3.25 3.5a.75.75 0 101.1 1.02l1.95-2.1v4.59z" clip-rule="evenodd" />
                    </svg>
                    <span><strong className="font-semibold text-gray-900">Recycling Performance Tracking</strong> The Rubbish Portal measures and tracks recycling performance at events, providing real-time insights into waste management efforts. This data-driven approach enables organisers to identify strengths and weaknesses in their recycling programs.</span>
                  </li>
                  <li className="flex gap-x-3">
                    <svg className="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M10 1a4.5 4.5 0 00-4.5 4.5V9H5a2 2 0 00-2 2v6a2 2 0 002 2h10a2 2 0 002-2v-6a2 2 0 00-2-2h-.5V5.5A4.5 4.5 0 0010 1zm3 8V5.5a3 3 0 10-6 0V9h6z" clip-rule="evenodd" />
                    </svg>
                    <span><strong className="font-semibold text-gray-900">Comparison & Ranking</strong> Our platform goes beyond simple tracking and offers the ability to compare and rank events based on their recycling results. This feature facilitates healthy competition among event organisers and encourages them to improve their recycling efforts continually.</span>
                  </li>
                  <li className="flex gap-x-3">
                    <svg className="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path d="M4.632 3.533A2 2 0 016.577 2h6.846a2 2 0 011.945 1.533l1.976 8.234A3.489 3.489 0 0016 11.5H4c-.476 0-.93.095-1.344.267l1.976-8.234z" />
                      <path fill-rule="evenodd" d="M4 13a2 2 0 100 4h12a2 2 0 100-4H4zm11.24 2a.75.75 0 01.75-.75H16a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75h-.01a.75.75 0 01-.75-.75V15zm-2.25-.75a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75H13a.75.75 0 00.75-.75V15a.75.75 0 00-.75-.75h-.01z" clip-rule="evenodd" />
                    </svg>
                    <span><strong className="font-semibold text-gray-900">Actionable Recommendations</strong> The Rubbish Portal offers actionable recommendations based on the collected data. These insights help event organisers make informed decisions and design effective waste management systems that optimise recycling rates.</span>
                  </li>
                  <li className="flex gap-x-3">
                    <svg className="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path d="M4.632 3.533A2 2 0 016.577 2h6.846a2 2 0 011.945 1.533l1.976 8.234A3.489 3.489 0 0016 11.5H4c-.476 0-.93.095-1.344.267l1.976-8.234z" />
                      <path fill-rule="evenodd" d="M4 13a2 2 0 100 4h12a2 2 0 100-4H4zm11.24 2a.75.75 0 01.75-.75H16a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75h-.01a.75.75 0 01-.75-.75V15zm-2.25-.75a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75H13a.75.75 0 00.75-.75V15a.75.75 0 00-.75-.75h-.01z" clip-rule="evenodd" />
                    </svg>
                    <span><strong className="font-semibold text-gray-900">Contribution to a Sustainable Future</strong> With a strong focus on reducing carbon emissions and minimising waste volume, The Rubbish Portal targets a minimum recycling rate of 75%. By using the platform, event organisers actively contribute to a more sustainable future.</span>
                  </li>
                </ul> */}
              </div>
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </>
  )
}

export const getServerSideProps = async (context: any) => {
  const session = await getSession({ req: context.req })

  if (session && session?.company_id != null) {
    return {
      redirect: {
        permanent: false,
        destination: '/'
      }
    }
  }

  return {
    props: {}
  }
}
