import { useRouter } from 'next/router'
import Head from 'next/head'

export default function Verify () {
  const router = useRouter()
  const { verificationurl }: { verificationurl?: string } = router.query
  console.log('verification URL', verificationurl)
  return (
        <>
            <Head>
                <title>Verify Email</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/Logo_White.svg" />
                <script src="/static/datafeeds/udf/dist/bundle.js" async />
            </Head>
            <div className="grid place-content-center bg-gradient-to-br from-navy to-deep_blue h-[100vh]">
                <div className="flex flex-col items-center text-white">
                    <div className="mt-0 mb-6 -mr-16">
                        <img width='300px' src="/Full_Logo.svg" />
                    </div>
                    <div className="text-2xl font-semibold mb-2">Welcome to Macrovesta</div>
                    <div className="text-xl">Click the button to verify your email</div>
                    <a className=" text-center mt-10 bg-white text-black rounded-xl px-4 py-2" href={verificationurl ?? '/api/auth/error?error=linkunknown'}>
                        Click to Verify
                    </a>
                </div>
            </div>
        </>
  )
}
